export const pathname = {
  HOME: "/",
  PRODUCTS: "/products",
  ABOUT: "/about",
  CONTACT: "/contact",
  CART: "/cart",
  PRODUCTSITEM: "/product/:codeid",
  STUDY: "/study",
  PROFILE: "/profile",
  FAVORITES: "/favorites",
  LOGIN: "/login",
  ALLTION: "/brands/alltion",
  ECOTRON: "/brands/ecotron",
  GRAPHY: "/brands/graphy",
  DENTIS: "/brands/dentis",
  PROMIS: "/brands/promis",
  AM2000PLUS: "/brands/alltion/am-2000-plus",
  AM2000: "/brands/alltion/am-2000",
  AM5000: "/brands/alltion/am-5000",
  ANGEL100: "/brands/alltion/angel-100",
  ANGEL100PRO: "/brands/alltion/angel-100-pro",
};
