export const pathname = {
  HOME: "/",
  PRODUCTS: "/products",
  ABOUT: "/about",
  CONTACT: "/contact",
  CART: "/cart",
  PRODUCTSITEM: "/product/:codeid",
  STUDY: "/study",
  PROFILE: "/profile",
  FAVORITES: "/favorites",
  LOGIN: "/login",
  ALLTION: "/brands/alltion",
  ECOTRON: "/brands/ecotron",
  GRAPHY: "/brands/graphy",
  DENTIS: "/brands/dentis",
  PROMIS: "/brands/promis",
  AM2000PLUS: "/brands/alltion/am2000-plus",
};
