export const pathname = {
  HOME: "/",
  PRODUCTS: "/products",
  ABOUT: "/about",
  CONTACT: "/contact",
  CART: "/cart",
  PRODUCTSITEM: "/product/:codeid",
  STUDY: "/study",
  PROFILE: "/profile",
  FAVORITES: "/favorites",
  LOGIN: "/login",
  ALLTION: "/alltion",
  ECOTRON: "/ecotron",
  GRAPHY: "/graphy",
  DENTIS: "/dentis",
  PROMIS: "/promis",
};
