import * as chairImages from "./assets/images/сhairs";

export const dentalItems = [
  {
    id: 1,
    title: "LUVIS DENTAL CHAIRS",
    price: 890,
    code: "CUR-5460",
    brand: "Curaprox",
    img: [
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
      chairImages.LUVIS_Chair_C_Class_Perspective,
    ],
    description: "",
  },
  {
    id: 2,
    title: "Паста Sensodyne Repair & Protect",
    price: 320,
    code: "SEN-RP01",
    brand: "Sensodyne",
    img: [
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
      chairImages.LUVIS_Chair_C_Class_Perspective,
    ],
  },
  {
    id: 3,
    title: "Ирригатор Waterpik WP-100",
    price: 7490,
    code: "WP-100",
    brand: "Waterpik",
    img: [
      chairImages.C_Class_unit_cart_후면,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
      chairImages.LUVIS_Chair_C_Class_Perspective,
    ],
  },
  {
    id: 4,
    title: "Зубная нить Oral-B Essential Floss",
    price: 150,
    code: "OB-EF10",
    brand: "Oral-B",
    img: [
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
      chairImages.LUVIS_Chair_C_Class_Perspective,
    ],
  },
  {
    id: 5,
    title: "Ополаскиватель Listerine Total Care",
    price: 410,
    code: "LTC-500",
    brand: "Listerine",
    img: [
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Front,
      chairImages.LUVIS_Chair_C_Class_Perspective,
    ],
  },
  {
    id: 6,
    title: "Полоски Crest 3D White",
    price: 2450,
    code: "C3D-WHITE",
    brand: "Crest",
    img: [
      chairImages.LUVIS_Chair_C_Class_Front,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Perspective,
    ],
  },
  {
    id: 7,
    title: "Гель Elmex Sensitive",
    price: 530,
    code: "ELM-SENS",
    brand: "Elmex",
    img: [
      chairImages.LUVIS_Chair_C_Class_Perspective,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
    ],
  },
  {
    id: 8,
    title: "Детская паста Splat Juicy",
    price: 180,
    code: "SPL-JC",
    brand: "Splat",
    img: [
      chairImages.LUVIS_Chair_C_Class_Side,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
    ],
  },
  {
    id: 9,
    title: "Электрощётка Philips Sonicare",
    price: 8990,
    code: "PH-SNCR",
    brand: "Philips",
    img: [
      chairImages.LUVIS_Chair_E_Class_Back,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
    ],
  },
  {
    id: 10,
    title: "Набор для путешествий DentalPro",
    price: 690,
    code: "DTP-KIT",
    brand: "DentalPro",
    img: [
      chairImages.s_Class_unit_cart,
      chairImages.C_Class_unit_cart_2,
      chairImages.C_Class_unit_cart_3,
      chairImages.C_Class_unit_cart_후면,
      chairImages.LUVIS_Chair_C_Class_Back,
      chairImages.LUVIS_Chair_C_Class_Front,
    ],
  },
];
